version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: openzeppelin-solidity
    versions:
    - 3.3.0
    - 3.4.0
    - 3.4.1
    - 4.0.0
  - dependency-name: web3
    versions:
    - 1.3.3
    - 1.3.4
  - dependency-name: eth-crypto
    versions:
    - 1.8.0
  - dependency-name: bn.js
    versions:
    - 5.1.3
  - dependency-name: lodash
    versions:
    - 4.17.20
